// This is an auto-generated file. You should not edit it manually

namespace Padoru.BattleArena
{
    public enum AudioFileId
    {
        BGMLevel = 0,
        BGMMenu = 1,
        BGMSummary = 2,
        Blackhole = 3,
        ButtonClick = 4,
        ButtonSelect = 5,
        CharacterSelectionSteps = 6,
        Dash = 7,
        Drop = 8,
        EndRound = 9,
        FireFistsBasic = 10,
        FireFistsDash = 11,
        FireFistsFloorPunch = 12,
        FireFistsUltimate = 13,
        HammerHit = 14,
        HammerThrow = 15,
        HammerThrowAirLoop = 16,
        HammerThrowCatch = 17,
        HammerUltimate = 18,
        LanternFire = 19,
        LifeDrainHit = 20,
        LifeDrainThrow = 21,
        MultipleVoidSphereCast = 22,
        PentagramExplosion = 23,
        PentagramSpawn = 24,
        PlayerDamage = 25,
        PlayerDeath = 26,
        PlayerSpawn = 27,
        PortalShatter = 28,
        RockWallDestroy = 29,
        RockWallSpawn = 30,
        RoundText = 31,
        SlowZoneIn = 32,
        SlowZoneOut = 33,
        StartRound = 34,
        TornadoLoop = 35,
        VaporPush = 36,
        VoidBallCast = 37,
        VoidBallHit = 38,
        VoidSphereCast = 39,
        VoidSphereHit = 40,
        WarningBeat = 41,
        ZoomIn = 42,
    }
}